function image = load_image(filename, clear_cache)
%Loads data from the csv ascii files produced by our camera software
%   
%   filename should be the name of the file with extension.  A relative or
%   absolute path may also be included in filename.
%   
%   clear_cache tells the function whether or not to clear data from the
%   hard drive read cache.  By default this is false. Results from reading
%   the hard drive are cached for speed.  Call this function with
%   clear_cache=true to clear the cache.  This is necessary if, for
%   example, data on the hard drive has changed and the new file should be
%   read in.  Also, once the cache is full, no more files are added to the
%   cache (currently we don't delete old cache entries to add new ones).
%   If you'd like to add new files to the cache but it is full, you must
%   clear it.  Caching of the inputs is done by treating it as a raw
%   string, so if two different paths to the same file are specified in two
%   different calls, the function will cache the result twice, once for
%   each given input string.
%
%   Example Usage:
%   >> image = load_image( fullfile('20170412','Savefile_45_back.ascii') ); %load an image
%   >> %clear cache (will error since no filename is provided, but cache
%   >> %will still be cleared)
%   >> image = load_image( '', true ); 

%Create persistent variable for storing memoized function
persistent cached_reader;
max_cache_size=10000; %Maximum number of files to cache

%If this is the first call, create the memoized function object
if isempty(cached_reader) 
    cached_reader=containers.Map;
end

%Clear the cache if instructed
if nargin<2
    clear_cache=false;
end
if clear_cache
    %Clear the memoization cache
    cached_reader=containers.Map;
    remove(cached_reader, keys(cached_reader) );
end

%Get the image data, using the cache if possible
if isKey(cached_reader,filename)
    %We have a cached result, so we'll return it
    image=cached_reader(filename);
else
    image=read_image_from_drive(filename);
    %add to cache if there's room
    if length(cached_reader)<max_cache_size
        cached_reader(filename)=image;
    end
end

%Uncomment the following line and comment the above code to ditch the
%memoizing stuff and just read from the hard drive
% image=read_image_from_drive(filename);

end

function image = read_image_from_drive(filename)
%Loads data from the csv ascii files produced by our camera software
%   image = load_image(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   image = load_image(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   NoAtomsAverage2 = load_image('NoAtomsAverage1.txt', 1, 121);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/09 17:43:35

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
%   column75: double (%f)
%	column76: double (%f)
%   column77: double (%f)
%	column78: double (%f)
%   column79: double (%f)
%	column80: double (%f)
%   column81: double (%f)
%	column82: double (%f)
%   column83: double (%f)
%	column84: double (%f)
%   column85: double (%f)
%	column86: double (%f)
%   column87: double (%f)
%	column88: double (%f)
%   column89: double (%f)
%	column90: double (%f)
%   column91: double (%f)
%	column92: double (%f)
%   column93: double (%f)
%	column94: double (%f)
%   column95: double (%f)
%	column96: double (%f)
%   column97: double (%f)
%	column98: double (%f)
%   column99: double (%f)
%	column100: double (%f)
%   column101: double (%f)
%	column102: double (%f)
%   column103: double (%f)
%	column104: double (%f)
%   column105: double (%f)
%	column106: double (%f)
%   column107: double (%f)
%	column108: double (%f)
%   column109: double (%f)
%	column110: double (%f)
%   column111: double (%f)
%	column112: double (%f)
%   column113: double (%f)
%	column114: double (%f)
%   column115: double (%f)
%	column116: double (%f)
%   column117: double (%f)
%	column118: double (%f)
%   column119: double (%f)
%	column120: double (%f)
%   column121: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
filename=strtrim(filename); %Vendeiro trim whitespace
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
image = [dataArray{1:end-1}];
end