function [ atom_OD_cheng ] = process_series_cheng(series_name, basis_cheng, back_region)
%Averages the images in the given series and removes the background using
%Cheng's algorithm
%   series_name should be the path and name of the series of images for one
%   sequence without '_raw.ascii' or any ending like that
%
%   basis_cheng should be a basis generated by make_basis_cheng()
%
%   back_region should the same back_region that was given to
%   make_basis_cheng() in order to generate the basis.  It should be a 2D
%   array with 1's in the pixels that should be considered as background
%   and used, and 0's in the pixels that should be ignored (e.g. if there
%   are atoms there).  The easiest way to make this matrix is to use
%   make_back_region().
%
%   atom_OD is a 2D array of the optical depth of the atoms with the
%   background removed.  It is the result of averaging all the data in the
%   series and removing the background using Cheng's algorithm
%
%   Example Usage:
%   >> series_name = fullfile('20170406','Savefile');
%   >> atom_OD = process_series_cheng(series_name,basis_cheng, back_region);

%Get a list of filenames for the series
atom_filename_pattern=[series_name,'_*_raw.ascii'];
atom_file_list=get_file_list(atom_filename_pattern);

%Now let's average all the images (you get pretty much the same results by
%doing the projection after averaging as when you do the projections before
%averaging, so we'll do it the faster way)
raw_mean=get_mean_image(atom_file_list);
atom_OD_cheng=get_OD_cheng(raw_mean,basis_cheng,back_region);
end

